version: '3'

volumes:
  db_data:

networks:
  network:

services:
  db:
    build:
      context: docker-db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    tty: true
    networks:
      - network

  web:
    build:
      context: docker-web
    volumes:
      - ./web-app-api:/web-app-api
    ports:
      - "3000:3000"
    tty: true
    networks:
      - network
    depends_on:
      - db
