version: '3.7'

volumes:
  db_data:
  api_vendor:
  api_root_bundle_cache:
  api_usr_local_bundle:
  ui_usr_lib_node_modules:

networks:
  app_network:

services:
  db:
    build:
      context: docker-db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    tty: true
    networks:
      - app_network

  api:
    build:
      context: docker-web
    environment:
      - BUNDLE_PATH=/web-app-api/vendor
    volumes:
      - ./web-app-api:/web-app-api
      - api_vendor:/web-app-api/vendor
      - api_root_bundle_cache:/root/.bundle/cache/
      - api_usr_local_bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    tty: true
    networks:
      - app_network
    depends_on:
      - db

  ui:
    build:
      context: docker-ui
    volumes:
      - ./web-app-ui:/web-app-ui
      - ui_usr_lib_node_modules:/usr/lib/node_modules/
    ports:
      - "4200:4200"
    tty: true
    networks:
      - app_network
    depends_on:
      - api
